### ISSUE TITLE
hexo deploy（部署网站操作失败）

### ISSUE THREAD

**Issue by xleonseven** [Wensibob/Wensibob.github.io#10]
你好，我在部署到github项目时出现错误

log：
FATAL bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument

Error: bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': Invalid argument

**Comment by Wensibob** [comment]
你这个问题应当是在_config.yml中的配置可能存在问题，我在网上查到的结局方案是，
把_config.yml中的repository 改了成了ssh，修改之后的_config.yml应该如下所示：
```
deploy:
  type: git
  repository: ssh://git@github.com/xxx/xxx.github.io
  branch: master
```
